name: Generate Documentation
on:
  push:
    branches:
      - "main"
      - "stable"

jobs:
  docs:
    name: Generate Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.4.0
        
      - name: Setup Go environment
        uses: actions/setup-go@v2.1.5
        with:
          go-version: 1.17

      - name: Get Docgen
        run: go get github.com/gominima/docgen 
        
      - name: Run Docgen
        run: go run github.com/gominima/docgen . $(git rev-parse --abbrev-ref HEAD).json
        
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/}.json)"
        id: extract_branch

      - name: Push docs file
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: ${{ steps.extract_branch.outputs.branch }}
          destination_repo: 'gominima/docs'
          user_email: 'tanumegatank@gmail.com'
          user_name: 'megatank58'
          commit_message: 'chore: docs'
        
