name: Generate Documentation
on:
  push:
    branches:
      - "main"
      - "stable"
  pull_request:
    branches:
      - "main"
      - "stable"

jobs:
  docs:
    name: Generate Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.4.0

      - name: Get Docgen
        run: go get github.com/gominima/docgen 
        
      - name: Run Docgen
        run: go run github.com/gominima/docgen . $(github.ref)

      - name: Pushes docs file
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: ${{ github.ref }}
          destination_repo: 'gominima/docs'
          user_email: 'tanumegatank@gmail.com'
          user_name: 'megatank58'
          commit_message: 'chore: docs'
        
